spring:
  application:
    name: service-track-checkout

mercado-pago:
  access-token: ${MERCADO_PAGO_ACCESS_TOKEN:}
  notification-url: ${MERCADO_PAGO_NOTIFICATION_URL:}

clients:
  integrations:
    ENVIAR_PAGAMENTO_PIX:
      url: ${URL_ENVIAR_PAGAMENTO_PIX:https://api.mercadopago.com/v1/payments}
      timeout: ${TIMEOUT_ENVIAR_PAGAMENTO_PIX:15000}
      retry: ${RETRY_ENVIAR_PAGAMENTO_PIX:2}
    ENVIAR_PAGAMENTO_BOLETO:
      url: ${URL_ENVIAR_PAGAMENTO_BOLETO:https://api.mercadopago.com/v1/payments}
      timeout: ${TIMEOUT_ENVIAR_PAGAMENTO_BOLETO:15000}
      retry: ${RETRY_ENVIAR_PAGAMENTO_BOLETO:2}
    ENVIAR_PAGAMENTO_CARTAO:
      url: ${URL_ENVIAR_PAGAMENTO_CARTAO:https://api.mercadopago.com/v1/payments}
      timeout: ${TIMEOUT_ENVIAR_PAGAMENTO_CARTAO:20000}
      retry: ${RETRY_ENVIAR_PAGAMENTO_CARTAO:0}
    CONSULTAR_PAGAMENTO:
      url: ${URL_CONSULTAR_PAGAMENTO:https://api.mercadopago.com/v1/payments}
      timeout: ${TIMEOUT_CONSULTAR_PAGAMENTO:10000}
      retry: ${RETRY_CONSULTAR_PAGAMENTO:3}
    CANCELAR_PAGAMENTO:
      url: ${URL_CANCELAR_PAGAMENTO:https://api.mercadopago.com/v1/payments}
      timeout: ${TIMEOUT_CANCELAR_PAGAMENTO:15000}
      retry: ${RETRY_CANCELAR_PAGAMENTO:2}
    ESTORNAR_PAGAMENTO:
      url: ${URL_ESTORNAR_PAGAMENTO:https://api.mercadopago.com/v1/payments}
      timeout: ${TIMEOUT_ESTORNAR_PAGAMENTO:15000}
      retry: ${RETRY_ESTORNAR_PAGAMENTO:2}
